// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkRQvsxoUvvG_k-3kxY8p55fjwegINTM',
    appId: '1:173997870344:web:fda390459bc809ff7530bd',
    messagingSenderId: '173997870344',
    projectId: 'moo-app-6485e',
    authDomain: 'moo-app-6485e.firebaseapp.com',
    databaseURL: 'https://moo-app-6485e-default-rtdb.firebaseio.com',
    storageBucket: 'moo-app-6485e.appspot.com',
    measurementId: 'G-RW4KS100XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCay6nq74b0ku0-p1MkjhiYlGJhIjWuIkA',
    appId: '1:173997870344:android:6bc0657e5b86e5437530bd',
    messagingSenderId: '173997870344',
    projectId: 'moo-app-6485e',
    databaseURL: 'https://moo-app-6485e-default-rtdb.firebaseio.com',
    storageBucket: 'moo-app-6485e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj41hXPk98YLSnAxJRv-eYHtcVGFykgiM',
    appId: '1:173997870344:ios:75b9847e5ec6450b7530bd',
    messagingSenderId: '173997870344',
    projectId: 'moo-app-6485e',
    databaseURL: 'https://moo-app-6485e-default-rtdb.firebaseio.com',
    storageBucket: 'moo-app-6485e.appspot.com',
    androidClientId: '173997870344-ujl5v03lnjm6ou5h98b7amt2kd3074gk.apps.googleusercontent.com',
    iosClientId: '173997870344-djs3mgi6btkqtbfh334fbkj04kvrqmon.apps.googleusercontent.com',
    iosBundleId: 'com.example.moo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj41hXPk98YLSnAxJRv-eYHtcVGFykgiM',
    appId: '1:173997870344:ios:75b9847e5ec6450b7530bd',
    messagingSenderId: '173997870344',
    projectId: 'moo-app-6485e',
    databaseURL: 'https://moo-app-6485e-default-rtdb.firebaseio.com',
    storageBucket: 'moo-app-6485e.appspot.com',
    androidClientId: '173997870344-ujl5v03lnjm6ou5h98b7amt2kd3074gk.apps.googleusercontent.com',
    iosClientId: '173997870344-djs3mgi6btkqtbfh334fbkj04kvrqmon.apps.googleusercontent.com',
    iosBundleId: 'com.example.moo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOkRQvsxoUvvG_k-3kxY8p55fjwegINTM',
    appId: '1:173997870344:web:c2812f0a46a119a47530bd',
    messagingSenderId: '173997870344',
    projectId: 'moo-app-6485e',
    authDomain: 'moo-app-6485e.firebaseapp.com',
    databaseURL: 'https://moo-app-6485e-default-rtdb.firebaseio.com',
    storageBucket: 'moo-app-6485e.appspot.com',
    measurementId: 'G-R28CTL7ZYB',
  );
}
